routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('lang/{lang}', 'LanguageController@index')->name('lang');

Route::group(['middleware' => 'language'], function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['middleware' => 'auth'], function () {
        Route::resource('users', 'UserController');
        Route::resource('sections', 'SectionController');
    });
});

app/Section.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Section extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'logo',
    ];

    /**
     * Section has many users
     *
     * @return BelongsToMany
     */
    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'user_section');
    }

    /**
     * Default logo
     */
    public function getDefaultLogoAttribute()
    {
        return asset('assets/images/default.png');
    }
}

app/Http/Controllers/SectionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreSectionRequest;
use App\Http\Requests\UpdateSectionRequest;
use App\Section;
use App\User;
use Exception;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpFoundation\RedirectResponse;

class SectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Renderable
     */
    public function index(): Renderable
    {
        return view('crud.sections.index', [
            'sections' => Section::with('users')->latest()->paginate(7)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Renderable
     */
    public function create(): Renderable
    {
        return view('crud.sections.create', [
            'users' => User::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreSectionRequest $request
     * @return RedirectResponse
     */
    public function store(StoreSectionRequest $request): RedirectResponse
    {
        DB::transaction(function () use ($request) {
            $section = Section::create([
                'name' => $request->title,
                'description' => $request->description,
                'logo' => $request->file('logo')->store('logo')
            ]);

            $section->users()->sync($request->users);
        });

        return redirect()
            ->route('sections.index')
            ->with('message', __('custom.crud.added', ['entity' => __('custom.user')]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Section $section
     * @return Renderable
     */
    public function edit(Section $section): Renderable
    {
        $sectionUsers = $section->users->pluck('id');

        $users = User::all()->map(function ($user) use ($sectionUsers) {
            if ($sectionUsers->contains($user->id)) {
                $user->setAttribute('checked', true);
            } else {
                $user->setAttribute('checked', false);
            }
            return $user;
        });

        return view('crud.sections.edit', [
            'section' => $section,
            'users' => $users
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateSectionRequest $request
     * @param Section $section
     * @return RedirectResponse
     */
    public function update(UpdateSectionRequest $request, Section $section): RedirectResponse
    {
        $data = ['name' => $request->title, 'description' => $request->description];

        if ($request->file('logo')) {
            $data['logo'] = $request->file('logo')->store('logo');
        }

        DB::transaction(function () use ($request, $section, $data) {
            $section->update($data);
            $section->users()->sync($request->users);
        });

        return redirect()
            ->route('sections.index')
            ->with('message', __('custom.crud.updated', ['entity' => __('custom.section')]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Section $section
     * @return RedirectResponse
     * @throws Exception
     */
    public function destroy(Section $section): RedirectResponse
    {
        $section->delete();

        return redirect()
            ->route('sections.index')
            ->with('message', __('custom.crud.deleted', ['entity' => __('custom.user')]));
    }
}

resources/views/crud/sections/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 pt-4 pb-4 d-flex justify-content-between">
                <h4>{{ __('custom.sections') }}</h4>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-12">
                <form action="{{ route('sections.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                        <label for="title" class="col-12 col-form-label">{{ __('custom.title') }}</label>

                        <div class="col-12">
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}">

                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="description" class="col-12 col-form-label">{{ __('custom.description') }}</label>

                        <div class="col-12">
                            <textarea class="form-control @error('description') is-invalid @enderror" id="description" rows="3" name="description">{{ old('description') }}</textarea>

                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-12">
                            <input type="file" name="logo" class="@error('logo') is-invalid @enderror">

                            @error('logo')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-12">
                            <h4>{{ __('custom.users') }}</h4>

                            @foreach($users as $user)
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="{{ $user->id }}" id="checkbox-{{ $user->id }}" name="users[]">
                                    <label class="form-check-label" for="checkbox-{{ $user->id }}">
                                        {{ $user->name }}
                                    </label>
                                </div>
                            @endforeach

                            @error('users')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">
                                {{ __('add') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/crud/sections/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 pt-4 pb-4 d-flex justify-content-between">
                <h4>{{ __('custom.sections') }}</h4>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-12">
                <form action="{{ route('sections.update', $section) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    {{ method_field('put') }}

                    <div class="form-group row">
                        <label for="title" class="col-12 col-form-label">{{ __('custom.title') }}</label>

                        <div class="col-12">
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') ?? $section->name }}">

                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="description" class="col-12 col-form-label">{{ __('custom.description') }}</label>

                        <div class="col-12">
                            <textarea class="form-control @error('description') is-invalid @enderror" id="description" rows="3" name="description">{{ old('description') ?? $section->description }}</textarea>

                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-12">
                            <input type="file" name="logo" value="{{ old('logo') ?? $section->logo }}">

                            @error('logo')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-12">
                            <h4>{{ __('custom.users') }}</h4>

                            @foreach($users as $user)
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="{{ $user->id }}" id="checkbox-{{ $user->id }}" name="users[]" {{ $user->checked ? 'checked' : '' }}>
                                    <label class="form-check-label" for="checkbox-{{ $user->id }}">
                                        {{ $user->name }}
                                    </label>
                                </div>
                            @endforeach

                            @error('users')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">
                                {{ __('add') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/crud/sections/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 pt-4 pb-4 d-flex justify-content-between">
                <h4>{{ __('custom.sections') }}</h4>
                <a class="btn btn-primary" href="{{ route('sections.create') }}">{{ __('custom.add') }}</a>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-12">
                @if($sections->isNotEmpty())
                    <table class="table">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">{{ __('custom.logo') }}</th>
                            <th scope="col">{{ __('custom.title') }}</th>
                            <th scope="col">{{ __('custom.users') }}</th>
                            <th scope="col">{{ __('custom.created_at') }}</th>
                            <th scope="col">{{ __('custom.actions') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($sections as $section)
                            <tr>
                                <th scope="row">{{ $section->id }}</th>
                                <td>
                                    <img class="crud-image" src="{{ '/storage/' . $section->logo ?? $section->default_logo }}" alt="">
                                </td>
                                <td>
                                    <div>{{ $section->name }}</div>
                                    <div>{{ $section->description }}</div>
                                </td>
                                <td>
                                    @if($section->users->isEmpty())
                                        {{ __('custom.nothing_found') }}
                                    @endif
                                    <ul>
                                        @foreach($section->users as $user)
                                            <li>{{ $user->name }}</li>
                                        @endforeach
                                    </ul>
                                </td>
                                <td>{{ $section->created_at }}</td>
                                <td>
                                    <div class="d-flex">
                                        <a class="btn btn-warning mr-2" href="{{ route('sections.edit', $section) }}">{{ __('custom.edit') }}</a>
                                        <form action="{{ route('sections.destroy', $section) }}" method="post">
                                            @csrf
                                            {{ method_field('delete') }}
                                            <button class="btn btn-danger" type="submit">{{ __('custom.delete') }}</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                    {{ $sections->links() }}
                @else
                    <div class="text-center">{{ __('custom.nothing_found') }}</div>
                @endif
            </div>
        </div>
    </div>
@endsection